# -*- coding: utf-8 -*-
"""automate_RifqiMakarim.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CR1j5MZh838M63QvF1YKjLXNZ7j4uyw
"""

import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder, StandardScaler

def preprocess_data(file_path):

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File {file_path} tidak ditemukan.")

    df = pd.read_csv(file_path, sep=';')
    df = df.drop_duplicates()

    # Label Encoding untuk Target 'y'
    le = LabelEncoder()
    if 'y' in df.columns:
        df['y'] = le.fit_transform(df['y'])

    # One-Hot Encoding untuk fitur kategorikal
    categorical_cols = df.select_dtypes(include=['object']).columns
    df_final = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

    # Scaling Fitur Numerik
    numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

    if 'y' in numerical_cols:
        numerical_cols.remove('y')

    scaler = StandardScaler()
    df_final[numerical_cols] = scaler.fit_transform(df_final[numerical_cols])

    return df_final

if __name__ == "__main__":
    input_file = 'bankmarketing_raw.csv'

    output_folder = 'preprocessing'

    os.makedirs(output_folder, exist_ok=True)
    output_file = os.path.join(output_folder, 'bank_preprocessed.csv')

    processed_df = preprocess_data(input_file)
    processed_df.to_csv(output_file, index=False)
